_wandb:
    value:
        cli_version: 0.21.4
        e:
            3wglw8alyxt718wvmgc3ql1k3bwcrozs:
                args:
                    - --model-config
                    - model_config.yaml
                    - --train-config
                    - train_config.yaml
                codePath: part1/train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "2000796545024"
                        used: "326691295232"
                email: murtaza.0903@gmail.com
                executable: /Users/veehive/cw2_2025_2026-students/.venv/bin/python
                git:
                    commit: bf40bd8efb135beebcdf51290196426238c1c5ff
                    remote: https://github.com/Mortza1/cw2_2025_2026-students.git
                host: Veehives-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-12.7.6-x86_64-i386-64bit
                program: /Users/veehive/cw2_2025_2026-students/part1/train.py
                python: CPython 3.10.19
                root: /Users/veehive/cw2_2025_2026-students/part1
                startedAt: "2025-11-22T13:16:09.952425Z"
                writerId: 3wglw8alyxt718wvmgc3ql1k3bwcrozs
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.21.4
            "6": 4.56.1
            "12": 0.21.4
            "13": darwin-x86_64
dev_batch_size:
    value: 128
dropout_rate:
    value: 0.2
embed_size:
    value: 128
hidden_size:
    value: 128
log_every:
    value: 10
lr:
    value: 0.001
lr_decay:
    value: 0.5
max_epoch:
    value: 30
max_num_trial:
    value: 5
patience:
    value: 1
seed:
    value: 0
train_batch_size:
    value: 32
uniform_init:
    value: 0.1
valid_niter:
    value: 2000
